# Generated by Django 3.1.6 on 2021-05-11 21:13

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210512_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='post_photos', validators=[utils.validators.validate_size, utils.validators.validate_extension]),
        ),
    ]
