# Generated by Django 3.1.6 on 2021-05-12 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210512_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='directed_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='main.comment'),
        ),
    ]
