# Generated by Django 3.1.6 on 2021-05-12 09:55

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210512_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='group_photos', validators=[utils.validators.validate_size, utils.validators.validate_extension]),
        ),
    ]
