# Generated by Django 3.1.6 on 2021-05-13 12:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_group_photo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together={('from_user', 'to_user')},
        ),
        migrations.AlterUniqueTogether(
            name='groupinvite',
            unique_together={('group', 'to_user')},
        ),
        migrations.AlterUniqueTogether(
            name='groupjoinrequest',
            unique_together={('from_user', 'to_group')},
        ),
    ]
