# Generated by Django 3.1.6 on 2021-05-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210513_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='message',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='groupinvite',
            name='message',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='groupjoinrequest',
            name='message',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
