# Generated by Django 3.1.6 on 2021-05-13 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_auto_20210513_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_friendrequests', related_query_name='incoming_friendrequest', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupinvite',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_groupinvites', to='main.group'),
        ),
        migrations.AlterField(
            model_name='groupinvite',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_groupinvites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupjoinrequest',
            name='to_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_groupjoinrequests', to='main.group'),
        ),
    ]
