# Generated by Django 3.1.6 on 2021-05-13 20:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_', '0007_auto_20210513_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='friends',
            field=models.ManyToManyField(related_name='_customuser_friends_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
